[package]
name = "newt"
version = "0.7.1"
authors = ["Robert Gill <rtgill82@gmail.com>"]
description = "Rust bindings for the Newt console UI library"
repository = "https://github.com/rtgill82/newt-rs"
license = "LGPL-2.1-only"
categories = ["api-bindings", "os::unix-apis"]
keywords = ["bindings", "tui"]
readme = "README.md"
edition = "2018"

[features]
static = ["newt-sys/static"]
asm    = []
f16    = []

[dependencies]
libc             = "0.2"
newt_proc_macros = "=0.0.16"
newt-sys         = "0.2"

[build-dependencies]
rustc_version = "0.4"

[dev-dependencies]
chrono   = "0.4"
rand     = "0.9"
tempfile = "3.0"

[package.metadata.docs.rs]
features = ["asm"]
