[package]
name = "newt_proc_macros"
version = "0.0.4"
authors = ["Robert Gill <locke@sdf.lonestar.org>"]
description = "Proc macros for newt-rs"
repository = "https://github.com/xelkarin/newt-rs"
license = "LGPL-2.0-only"

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
