[package]
name = "newt_proc_macros"
version = "0.0.7"
authors = ["Robert Gill <rtgill82@gmail.com>"]
description = "Proc macros for newt-rs"
repository = "https://github.com/rtgill82/newt-rs"
license = "LGPL-2.0-only"

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
